import type { Metadata } from "next"; 
//requires importing type since TS
//no other types are used in this file
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{
  children: React.ReactNode;
}>) {

  // here, the classname is taken from the imported inter fiule
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
      <p>this is just a test test test</p>
    </html>
  );
}
